# Generated by Django 3.2.9 on 2021-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='msg_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
