# Generated by Django 3.2.9 on 2021-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
