# Generated by Django 3.2.9 on 2021-12-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211213_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdd',
        ),
    ]
