# Generated by Django 3.2.9 on 2021-12-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20211213_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='user_image',
            field=models.ImageField(blank=True, default='defaultprofile.jpg', null=True, upload_to='profile/'),
        ),
    ]
