# Generated by Django 3.2.9 on 2022-01-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20211214_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='profile_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
