# Generated by Django 3.2.9 on 2022-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_useradd_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
