# Generated by Django 3.2.9 on 2022-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_useradd_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='profile_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
